
import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, doc, setDoc, addDoc, query, where, updateDoc, writeBatch, deleteDoc, getDoc } from "firebase/firestore/lite";
import fs from "fs";
import { GoogleGenAI } from "@google/genai";

let aiClient: any = null;
function getAiClient() {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    aiClient = new GoogleGenAI({
      apiKey: apiKey || "dummy_key",
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

// Safely load local config generated by AI Studio without breaking Vercel builds if the file is ignored
let db: any = null;

function getDb() {
  if (db) return db;

  let firebaseConfig: any = {};
  try {
    firebaseConfig = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'firebase-applet-config.json'), 'utf8'));
  } catch (e: any) {
    console.warn("Could not load local firebase config in api route.");
  }

  const finalConfig = {
    projectId: process.env.VITE_FIREBASE_PROJECT_ID || firebaseConfig.projectId || 'demo-project',
    appId: process.env.VITE_FIREBASE_APP_ID || firebaseConfig.appId || '1:1234567890:web:1234567890',
    apiKey: process.env.VITE_FIREBASE_API_KEY || firebaseConfig.apiKey || 'demo-api-key',
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfig.authDomain || 'demo-project.firebaseapp.com',
    firestoreDatabaseId: process.env.VITE_FIREBASE_DATABASE_ID || firebaseConfig.firestoreDatabaseId || '(default)',
  };

  const appFirebase = initializeApp(finalConfig);
  db = getFirestore(appFirebase, finalConfig.firestoreDatabaseId);
  return db;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Helper for checking dev environment api key
  const validateApiKey = (req, res, next) => {
    const authHeader = req.headers.authorization;
    if (authHeader && authHeader.startsWith('Bearer ')) {
      // In a real app we'd query db for the API key to find the schoolId
      // For now, we'll extract it assuming it's passed or default to dev
      req.schoolId = "dev-school";
      next();
    } else {
      res.status(401).json({ error: 'Unauthorized' });
    }
  };

  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

// --- GEMINI AI CENTER ENDPOINT ---
function generateFallbackNaCCADoc(type: string, schoolName: string, params: any) {
  if (type === 'lesson-plan') {
    const { level, subject, strand, subStrand, contentStandard, indicator, topic, duration, classSize, tlms } = params || {};
    return `### NaCCA STANDARD-BASED LESSON PLAN
**SCHOOL:** ${schoolName || "Ghana Basic School"}
**CLASS/LEVEL:** ${level || "Basic 7 (JHS 1)"} | **SUBJECT:** ${subject || "Integrated Science"}
**DURATION:** ${duration || "60 Mins"} | **CLASS SIZE:** ${classSize || "45 Learners"}
**STRAND:** ${strand || "Diversity of Matter"}
**SUB-STRAND:** ${subStrand || "Living and Non-Living Things"}
**CONTENT STANDARD:** ${contentStandard || "B7.1.1.1"}
**PERFORMANCE INDICATOR:** ${indicator || "B7.1.1.1.1 - Demonstrate understanding of cell structures"}
**CORE COMPETENCIES:** Critical Thinking, Problem Solving, Communication and Collaboration.
**TLMs:** ${tlms || "Microscope diagrams, plant and animal cell wall charts, onion skin slides, realia."}

---

#### PHASE 1: STARTER / WARM-UP (10 MINS)
1. **Prior Knowledge Check:** Ask learners to list basic living organisms in their local community.
2. **Hook Activity:** Display an onion and ask learners what tiny units build up the entire onion.
3. **Learning Target Statement:** By the end of this lesson, learners will identify and describe the basic parts of plant and animal cells.

#### PHASE 2: MAIN / TEACHING & LEARNING ACTIVITIES (35 MINS)
1. **Step 1 (Teacher Demonstration):** Explain the cell as the basic structural and functional unit of life.
2. **Step 2 (Group Investigation):** Divide learners into small mixed-gender groups. Provide cell wall charts and ask groups to compare plant and animal cells.
3. **Step 3 (Learner Presentation):** Group representatives present their findings on cell organelles (nucleus, cytoplasm, cell membrane).
4. **Step 4 (Differentiation & Inclusion):** Assist learners who require visual reinforcement using enlarged cell diagrams.

#### PHASE 3: PLENARY / REFLECTION & ASSESSMENT (15 MINS)
1. **Summary Review:** Review key differences between plant and animal cells with rapid-fire questions.
2. **Class Exercise / Assessment:**
   - Define a cell.
   - List two functions of the cell membrane.
3. **Home Project:** Draw and label a plant cell neatly in exercise books.`;
  } else if (type === 'scheme-of-learning') {
    const { level, subject, term, totalWeeks } = params || {};
    return `### NaCCA SCHEME OF LEARNING (SOL)
**SCHOOL:** ${schoolName || "Ghana Basic School"}
**CLASS/LEVEL:** ${level || "Basic 8"} | **SUBJECT:** ${subject || "Mathematics"}
**ACADEMIC TERM:** Term ${term || "1"} | **DURATION:** ${totalWeeks || 12} Weeks

| Week | Strand & Sub-strand | Content Standard & Indicator | Topic / Focus | Key TLMs | Assessment |
| --- | --- | --- | --- | --- | --- |
| **Week 1** | Number & Numeration | B8.1.1.1 (B8.1.1.1.1) | Real Number Systems & Sets | Charts, Venn Diagrams | Class Test 1 |
| **Week 2** | Number & Numeration | B8.1.1.2 (B8.1.1.2.1) | Prime Factors & Multiples | Prime Factor Trees | Group Assignment |
| **Week 3** | Algebra & Patterns | B8.2.1.1 (B8.2.1.1.1) | Algebraic Expressions | Grid Sheets, Counters | Board Exercise |
| **Week 4** | Algebra & Patterns | B8.2.1.2 (B8.2.1.2.1) | Linear Equations in 1 Variable | Balance Scale Models | Written Quiz |
| **Week 5** | Geometry & Measurement | B8.3.1.1 (B8.3.1.1.1) | Angles & Lines Geometry | Protractors, Rulers | Practical Drawing |
| **Week 6** | Mid-Term Assessment | Mid-Term Revision & Evaluation | Comprehensive Term Review | Answer Sheets | Mid-Term Exam |
| **Week 7** | Geometry & Measurement | B8.3.2.1 (B8.3.2.1.1) | Perimeter & Area of Shapes | Metric Rules, Cut-outs | Problem Set |
| **Week 8** | Handling Data | B8.4.1.1 (B8.4.1.1.1) | Frequency Tables & Tallies | Survey Sheets | Group Project |
| **Week 9** | Handling Data | B8.4.1.2 (B8.4.1.2.1) | Bar Graphs & Pie Charts | Graph Books, Color Pens | Graph Plotting |
| **Week 10** | Revision & Remediation | Revision of Difficult Concepts | BECE / WAEC Past Questions | Past Papers | Class Competition |
| **Week 11** | End of Term Examinations | Terminal Evaluation | Comprehensive Assessment | Question Papers | Terminal Exam |
| **Week 12** | Vacation & Marking | Report Cards & Parent Consultation | Performance Analysis | Cumulative Records | Parents Conference |`;
  } else if (type === 'exam-paper') {
    const { level, subject, topic, mcqCount, theoryCount, difficulty, includeAnswers } = params || {};
    return `### ${schoolName || "GHANA BASIC SCHOOL"}
**TERMINAL EXAMINATION - ACADEMIC TERM**
**SUBJECT:** ${subject || "Social Studies"} | **CLASS:** ${level || "Basic 9 (JHS 3)"}
**TIME ALLOWED:** 1 HOUR 30 MINUTES | **DIFFICULTY:** ${difficulty || "BECE Standard"}
**TOPIC / SCOPE:** ${topic || "Comprehensive Term Scope"}

---

#### SECTION A: MULTIPLE CHOICE QUESTIONS (Answer ALL questions)

1. Which organ of government is primarily responsible for making laws in Ghana?
   A) The Executive  B) The Judiciary  C) Parliament  D) The Council of State

2. The traditional leader who heads a paramount chieftaincy area in Ghana is known as:
   A) Divisional Chief  B) Paramount Chief (Omanhene)  C) Development Chief  D) Clan Head

3. Which of the following is a key requirement for promoting national unity in Ghana?
   A) Tribalism  B) Tolerance and respect for diversity  C) Nepotism  D) Political conflict

4. Environmental degradation in mining areas can be controlled effectively through:
   A) Deforestation  B) Illegal galamsey  C) Land reclamation and reforestation  D) Bush burning

5. The main objective of establishing the Economic Community of West African States (ECOWAS) is to:
   A) Fight wars  B) Promote regional economic integration  C) Rule West Africa  D) Impose taxes

---

#### SECTION B: STRUCTURED & ESSAY QUESTIONS (Answer ALL questions)

**QUESTION 1**
a) Define the term **Chieftaincy** as practiced in Ghana. *(4 marks)*
b) State and explain **three** functions of traditional authorities in national development. *(6 marks)*

**QUESTION 2**
a) Explain **two** causes of rural-urban migration in Ghana. *(4 marks)*
b) Suggest **three** measures government can put in place to curb rural-urban migration. *(6 marks)*

${includeAnswers ? `---

#### TEACHER'S MARKING SCHEME & MODEL ANSWERS

**SECTION A ANSWERS:**
1. C (Parliament) | 2. B (Paramount Chief) | 3. B (Tolerance) | 4. C (Reforestation) | 5. B (Regional Integration)

**SECTION B MODEL ANSWERS:**
- **Q1a:** Chieftaincy is an ancient system of governance where traditional leaders (chiefs and queenmothers) rule over customary territories according to native law and customs.
- **Q1b:** 1) Preservation of cultural heritage. 2) Maintenance of peace and conflict resolution. 3) Mobilizing community labor for local development projects.` : ''}`;
  } else if (type === 'remarks') {
    const { studentName, level, gender, score, attendance, conduct, competencies } = params || {};
    return `### TERMINAL REPORT REMARKS & PARENT ADVICE
**LEARNER NAME:** ${studentName || "Kwame Boateng"} | **GENDER:** ${gender || "Learner"}
**CLASS:** ${level || "Basic 7"} | **OVERALL SCORE:** ${score || "85% (Grade A)"}
**ATTENDANCE:** ${attendance || "58/60 Days"} | **CONDUCT:** ${conduct || "Polite and obedient"}

---

#### 1. CLASS TEACHER'S REMARK
${studentName} is an exceptional, disciplined, and hardworking learner who consistently demonstrates academic excellence. ${gender === 'Female' ? 'She' : 'He'} engages actively during class discussions and exhibits remarkable leadership traits among peers. With sustained focus and dedication, ${gender === 'Female' ? 'she' : 'he'} will continue to achieve top honors.

#### 2. HEADTEACHER'S ENDORSEMENT
An outstanding terminal performance. ${studentName} is commended for exemplary behavior, punctuality, and academic distinction. Keep up the brilliant effort!

#### 3. TAILORED ADVICE TO PARENTS / GUARDIANS
1. **Academic Support:** Encourage ${studentName} to maintain a daily 2-hour home reading schedule, particularly in analytical subjects.
2. **Co-curricular Encouragement:** Support ${studentName}'s involvement in STEM/Science club activities to nurture observed critical thinking skills.
3. **Administrative Note:** Please ensure all termly educational materials and school fees are prepared promptly ahead of reopening.`;
  } else if (type === 'circular') {
    const { purpose, keyDates, venue, feeOrDetails } = params || {};
    return `### ${schoolName || "GHANA EDUCATIONAL COMPLEX"}
**OFFICIAL CIRCULAR TO PARENTS & GUARDIANS**
**DATE:** ${new Date().toLocaleDateString('en-GB')} | **REF:** GEC/CIRC/${new Date().getFullYear()}/04

**SUBJECT:** ${purpose || "End of Term Vacation & School Reopening Announcement"}

Dear Parents & Guardians,

Management and staff extend our warmest greetings and heartfelt gratitude for your continued partnership and trust in educating your children at ${schoolName || "Ghana Educational Complex"}.

As we successfully conclude the current academic term, please take note of the following vital announcements:

1. **VACATION & REOPENING DATES:**
   - **Vacation Date:** ${keyDates?.split('|')[0] || "15th August"}
   - **Reopening Date:** ${keyDates?.split('|')[1] || "10th September"}

2. **PARENTS-TEACHERS ASSOCIATION (PTA) MEETING:**
   - **Venue:** ${venue || "School Main Assembly Hall"}
   - All parents are encouraged to attend as important academic progress and facility upgrade plans will be discussed.

3. **FINANCIAL & FEE PAYMENT INSTRUCTIONS:**
   - ${feeOrDetails || "School fees for the upcoming term must be paid into the school's official account or via MoMo before reopening."}

We wish all our learners a restful and enjoyable vacation.

Yours faithfully,

_______________________
**Headteacher / Administration**
${schoolName || "Ghana Educational Complex"}`;
  } else {
    return `### NaCCA AI TEACHER ASSISTANT
Thank you for your inquiry regarding Ghana's Standard-Based Curriculum (SBC) and Common Core Programme (CCP).

**Key Guidance:**
1. Focus on learner-centered activities and group investigations.
2. Utilize locally available Teaching and Learning Materials (TLMs) such as bottle caps, counters, charts, and realia.
3. Develop core competencies: Critical Thinking, Problem Solving, Communication, Collaboration, and Cultural Identity.`;
  }
}

  app.post("/api/v1/ai/generate", async (req: any, res: any) => {
    try {
      const { type, schoolName, params } = req.body || {};
      const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;

      if (apiKey) {
        try {
          const ai = getAiClient();
          const systemInstruction = "You are an expert Ghanaian Education Specialist, Curriculum Developer, and NaCCA (National Council for Curriculum and Assessment) Lead Consultant. You specialize in Ghana's Standard-Based Curriculum (SBC) for Kindergarten & Primary schools, and Common Core Programme (CCP) for Junior High Schools (JHS 1-3). Your outputs are professional, accurate, culturally contextualized for Ghana, and immediately usable by Ghanaian teachers and school leaders.";

          let prompt = "";

          if (type === 'lesson-plan') {
            const { level, subject, strand, subStrand, contentStandard, indicator, topic, duration, classSize, tlms } = params || {};
            prompt = `Generate a comprehensive, ready-to-use NaCCA Lesson Plan in standard Ghanaian school format:
School Name: ${schoolName || "Ghana Basic School"}
Class/Level: ${level || "Basic 7 (JHS 1)"}
Subject: ${subject || "Integrated Science"}
Strand: ${strand || "Diversity of Matter"}
Sub-strand: ${subStrand || "Living and Non-Living Things"}
Content Standard: ${contentStandard || "B7.1.1.1"}
Indicator / Code: ${indicator || "B7.1.1.1.1"}
Topic / Lesson Title: ${topic || "Cells as Basic Units of Life"}
Duration: ${duration || "60 mins"}
Class Size: ${classSize || "45 learners"}
TLMs (Teaching Materials): ${tlms || "Microscope diagrams, charts of plant and animal cells, onion skin slides, realia"}

Format output with clean markdown headers and bullet points:
1. HEADER DETAILS (Class, Subject, Duration, Strand, Sub-strand, Content Standard, Performance Indicator, Core Competencies e.g. Critical Thinking & Problem Solving, Key Words, TLMs)
2. PHASE 1: STARTER / WARM-UP (5-10 mins) - Prior knowledge check, engaging hook, learning target statement.
3. PHASE 2: MAIN / TEACHING & LEARNING ACTIVITIES (30-40 mins) - Detailed Step 1, Step 2, Step 3, Step 4 with teacher actions, learner activities, group work, and differentiation for diverse learners.
4. PHASE 3: PLENARY / REFLECTION & ASSESSMENT (5-10 mins) - Summary review questions, self-reflection, and Homework/Project work.`;
          } else if (type === 'scheme-of-learning') {
            const { level, subject, term, totalWeeks } = params || {};
            prompt = `Generate a detailed NaCCA Scheme of Learning (SOL) for Ghana Schools:
Class/Level: ${level || "Basic 8 (JHS 2)"}
Subject: ${subject || "Mathematics"}
Term: Term ${term || "1"}
Total Weeks: ${totalWeeks || 12} Weeks

Produce a week-by-week table/breakdown covering all ${totalWeeks || 12} weeks in Term ${term || 1}. For each week include:
- Week Number
- Strand & Sub-strand
- Content Standard Code & Indicator
- Topic / Focus
- Recommended Resources / TLMs
- Core Competencies Developed
- Assessment Method`;
          } else if (type === 'exam-paper') {
            const { level, subject, topic, mcqCount, theoryCount, difficulty, includeAnswers } = params || {};
            prompt = `Create a complete Terminal Examination / Assessment Test Paper adhering to Ghanaian NaCCA & WAEC/BECE standards:
School: ${schoolName || "Basic School"}
Class/Level: ${level || "Basic 9 (JHS 3)"}
Subject: ${subject || "Social Studies"}
Topic / Scope: ${topic || "Comprehensive Term Work / BECE Revision"}
Difficulty Level: ${difficulty || "BECE Standard"}
Number of MCQs (Section A): ${mcqCount || 10}
Number of Structured/Theory Questions (Section B): ${theoryCount || 3}
Include Marking Scheme: ${includeAnswers ? "YES" : "NO"}

Format cleanly with:
- School Exam Header (Title, Subject, Class, Time Allowed: e.g. 1 Hour 30 Mins, Total Marks)
- SECTION A: MULTIPLE CHOICE QUESTIONS (1-${mcqCount || 10} with options A, B, C, D)
- SECTION B: STRUCTURED & THEORY QUESTIONS (Questions 1-${theoryCount || 3} with sub-parts e.g. 1a, 1b, 2a...)
${includeAnswers ? "- TEACHER'S MARKING SCHEME & MODEL ANSWERS (Clearly separated at the end with point allocation)" : ""}`;
          } else if (type === 'remarks') {
            const { studentName, level, gender, score, attendance, conduct, competencies } = params || {};
            prompt = `Generate personalized, encouraging, and actionable Terminal Report Remarks & Advice to Parents for a Ghanaian learner:
Student Name: ${studentName || "Kwame Mensah"}
Gender: ${gender || "Learner"}
Class/Level: ${level || "Basic 6"}
Overall Score/Grade: ${score || "84% (Grade A - Excellent)"}
Attendance & Punctuality: ${attendance || "58/60 days - Regular and Punctual"}
Conduct/Attitude: ${conduct || "Polite, well-behaved, active in class"}
Observed Competencies/Traits: ${competencies || "Strong logical reasoning, cooperative team player"}

Provide:
1. CLASS TEACHER'S REMARK (3-4 sentences highlighting academic performance, character, and areas for growth)
2. HEADTEACHER'S ENDORSEMENT REMARK (2 concise formal sentences)
3. TAILORED ADVICE TO PARENTS / GUARDIANS (3 actionable recommendations for supporting the child at home, e.g. establishing evening reading hours, monitoring homework, encouraging participation in science clubs, ensuring fee payment prior to reopening)`;
          } else if (type === 'circular') {
            const { purpose, keyDates, venue, feeOrDetails } = params || {};
            prompt = `Draft an official School Circular / Notice to Parents for a Ghanaian school:
School Name: ${schoolName || "Ghana Educational Complex"}
Purpose / Topic: ${purpose || "End of Term Vacation & Reopening Announcement"}
Key Dates: ${keyDates || "Vacation: 15th August, Reopening: 10th September"}
Venue / Location: ${venue || "School Main Assembly Hall"}
Additional Details / Fees: ${feeOrDetails || "Next Term School Fees: GHS 850 payable via Mobile Money or Bank Deposit"}

Write a polite, formal letter addressed to "Dear Parents & Guardians", signed by the Headteacher, structured with formal Ghanaian administrative tone, clear headings, bullet points for key dates/requirements, and warm closing phrases.`;
          } else if (type === 'chat') {
            const { query, level, subject } = params || {};
            prompt = `As an expert Ghanaian NaCCA Teacher Assistant and Education Specialist, answer this teacher's question in a practical, helpful manner:
Context Level: ${level || "Basic School"}
Subject: ${subject || "General"}
Question / Request: ${query || "How can I teach fractions using low-cost Ghanaian local materials?"}

Provide concrete strategies, local Ghanaian teaching materials (TLMs e.g., bottle caps, plantain leaves, orange slices, coconut shells), classroom examples, and pedagogical advice.`;
          } else {
            return res.status(400).json({ error: "Invalid type requested" });
          }

          const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
              systemInstruction,
              temperature: 0.7,
            }
          });

          if (response && response.text) {
            return res.json({ result: response.text });
          }
        } catch (apiErr: any) {
          console.warn("Gemini API call warning, using NaCCA template fallback:", apiErr?.message);
        }
      }

      // Fallback if no GEMINI_API_KEY or if API call encountered error
      const fallbackResult = generateFallbackNaCCADoc(type, schoolName, params);
      return res.json({ result: fallbackResult });
    } catch (err: any) {
      console.error("Gemini AI error:", err);
      res.status(500).json({ error: err?.message || "Failed to generate AI content" });
    }
  });

  // --- SCHOOLS ---
  app.get("/api/v1/schools", async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "schools"));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/schools", async (req, res) => {
    try {
      const { name, region, district, email, password } = req.body;
      const school = {
        name, region, district, email,
        status: "Active", accessLevel: "Trial",
        userId: "admin-id", // mock
        createdAt: new Date().toISOString()
      };
      const docRef = await addDoc(collection(getDb(), "schools"), school);
      res.status(201).json({ ...school, id: docRef.id });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.get("/api/v1/schools/:id", async (req, res) => {
    try {
      const docRef = doc(getDb(), "schools", req.params.id);
      const snapshot = await getDoc(docRef);
      if (snapshot.exists()) {
        res.json({ ...snapshot.data(), id: snapshot.id });
      } else {
        res.status(404).json({ error: "School not found" });
      }
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/schools/:id", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), req.body, { merge: true });
      const docSnap = await getDoc(doc(getDb(), "schools", req.params.id));
      if (docSnap.exists()) {
        res.json({ ...docSnap.data(), id: docSnap.id });
      } else {
        res.json({ ...req.body, id: req.params.id });
      }
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- AUTH ---
  app.post("/api/v1/auth/login", async (req, res) => {
    try {
      const { email, password, role } = req.body;
      if (email === "superadmin@ges.gov.gh") {
        return res.json({
          success: true,
          user: { email, fullName: "Super Admin", role: "SuperAdmin" },
          school: {
            id: 'superadmin-ges',
            name: 'GES Super Admin Console',
            slug: 'ges-super-admin',
            region: 'National',
            district: 'HQ',
            email: 'superadmin@ges.gov.gh',
            status: 'Active',
            accessLevel: 'Full',
            createdAt: new Date().toISOString()
          },
          role: "SuperAdmin"
        });
      }

      const snapshot = await getDocs(query(collection(getDb(), "schools"), where("email", "==", email)));
      if (snapshot.empty) {
        return res.status(401).json({ error: "Invalid credentials" });
      }
      const schoolDoc = snapshot.docs[0];
      res.json({
        success: true,
        user: { email, fullName: "Admin User", role },
        school: { ...schoolDoc.data(), id: schoolDoc.id }
      });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });


  // --- STUDENTS ---
  app.get("/api/v1/students", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "students"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/students/:id", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "students", req.params.id), req.body);
      const docSnap = await getDoc(doc(getDb(), "students", req.params.id));
      if (docSnap.exists()) {
        res.json({ ...docSnap.data(), id: docSnap.id });
      } else {
        res.json({ ...req.body, id: req.params.id });
      }
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.delete("/api/v1/students/:id", async (req, res) => {
    try {

      
      const docRef = doc(getDb(), "students", req.params.id);
      const docSnap = await getDoc(docRef);
      if (docSnap.exists()) {
        const student = docSnap.data();
        await deleteDoc(docRef);
        
        if (student.schoolId) {
          const schoolRef = doc(getDb(), "schools", student.schoolId);
          const schoolSnap = await getDoc(schoolRef);
          if (schoolSnap.exists()) {
            const currentCount = schoolSnap.data().studentCount || 0;
            await updateDoc(schoolRef, { studentCount: Math.max(0, currentCount - 1) });
          }
        }
      }
      
      res.json({ message: "Student deleted" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students", async (req, res) => {
    try {
      const student = req.body;
      student.createdAt = new Date().toISOString();

      if (!student.admissionNo || student.admissionNo === "PENDING-SYNC") {
        student.admissionNo = `ADM-${Math.floor(Math.random() * 1000000).toString().padStart(6, '0')}`;
      }
      delete student.id;
      const docRef = await addDoc(collection(getDb(), "students"), student);
      
      // Update school student count
      if (student.schoolId) {
        const schoolRef = doc(getDb(), "schools", student.schoolId);
        const schoolSnap = await getDoc(schoolRef);
        if (schoolSnap.exists()) {
          const currentCount = schoolSnap.data().studentCount || 0;
          await updateDoc(schoolRef, { studentCount: currentCount + 1 });
        }
      }
      
      res.status(201).json({ ...student, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students/bulk", async (req, res) => {
    try {
      const { students } = req.body;

      const batch = writeBatch(getDb());
      const results = [];
      for (const s of students) {
        const docRef = doc(collection(getDb(), "students"));
        s.createdAt = new Date().toISOString();
        delete s.id;
        batch.set(docRef, s);
        results.push({ ...s, id: docRef.id });
      }
      await batch.commit();
      
      // Update school count
      if (students.length > 0 && students[0].schoolId) {
        const schoolRef = doc(getDb(), "schools", students[0].schoolId);
        const schoolSnap = await getDoc(schoolRef);
        if (schoolSnap.exists()) {
          const currentCount = schoolSnap.data().studentCount || 0;
          await updateDoc(schoolRef, { studentCount: currentCount + students.length });
        }
      }
      
      res.status(201).json(results);
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students/promote", async (req, res) => {
    try {
      const { studentIds, targetClass } = req.body;
      const batch = writeBatch(getDb());
      for (const id of studentIds) {
        batch.update(doc(getDb(), "students", id), { classLevel: targetClass });
      }
      await batch.commit();
      res.json({ message: "Promoted successfully" });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.get("/api/v1/sis/students", validateApiKey, async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "students"));
      res.json({ data: snapshot.docs.map(d => ({ ...d.data(), id: d.id })) });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  // --- PAYMENTS ---
  app.get("/api/v1/payments", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.studentId) conditions.push(where("studentId", "==", q.studentId as string));
      const snapshot = await getDocs(query(collection(getDb(), "payments"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/payments", async (req, res) => {
    try {
      const payment = req.body;
      payment.timestamp = new Date().toISOString();

      const docRef = await addDoc(collection(getDb(), "payments"), payment);
      res.status(201).json({ ...payment, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- BACKUPS ---
  app.get("/api/v1/backups", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "backupLogs"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/backups", async (req, res) => {
    try {
      const { schoolId, type } = req.body;
      const log = {
        schoolId, type: type || "Manual", timestamp: new Date().toISOString(),
        recordsCount: 0, fileName: `backup_${schoolId}_${Date.now()}.json`, status: "Completed"
      };
      const docRef = await addDoc(collection(getDb(), "backupLogs"), log);
      res.status(201).json({ log: { ...log, id: docRef.id } });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- API KEYS ---
  app.get("/api/v1/api-keys", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "apiKeys"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/api-keys", async (req, res) => {
    try {
      const { schoolId, name } = req.body;
      const key = {
        schoolId, name, status: "Active",
        token: `geda_tok_${Math.random().toString(36).substr(2, 9)}`,
        createdAt: new Date().toISOString()
      };
      const docRef = await addDoc(collection(getDb(), "apiKeys"), key);
      res.status(201).json({ ...key, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/api-keys/revoke", async (req, res) => {
    try {
      const { keyId } = req.body;
      if (keyId.startsWith("demo-key-")) return res.json({ message: "Revoked" });
      await updateDoc(doc(getDb(), "apiKeys", keyId), { status: "Revoked" });
      res.json({ message: "Revoked" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- OTHERS ---
  app.get("/api/v1/attendance", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.date) conditions.push(where("date", "==", q.date));
      if (q.studentId) conditions.push(where("studentId", "==", q.studentId));
      if (q.academicYear) conditions.push(where("academicYear", "==", q.academicYear));
      if (q.academicTerm) conditions.push(where("academicTerm", "==", q.academicTerm));
      const snapshot = await getDocs(query(collection(getDb(), "attendance"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/attendance/batch", async (req, res) => {
    try {
      const { schoolId, records } = req.body;
      const batch = writeBatch(getDb());
      for (const r of records) {
        // Enforce deterministic ID based on student and date to prevent any cross-contamination, leakage or duplicates
        const docId = `${r.studentId}_${r.date}`;
        const docRef = doc(getDb(), "attendance", docId);
        batch.set(docRef, { ...r, id: docId }, { merge: true });
      }
      await batch.commit();
      res.json({ message: "Attendance marked" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/sync", async (req, res) => {
    try {
      const { schoolId, students } = req.body;
      let syncedCount = 0;

      const batch = writeBatch(getDb());
      for (const s of students) {
        const docRef = doc(collection(getDb(), "students"));
        s.createdAt = s.createdAt || new Date().toISOString();
        s.syncStatus = "synced";
        delete s.id; // Remove offline ID
        batch.set(docRef, s);
        syncedCount++;
      }
      if (syncedCount > 0) {
        await batch.commit();
      }
      
      const snapshot = await getDocs(query(collection(getDb(), "students"), where("schoolId", "==", schoolId || "")));
      const allStudents = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));
      
      res.json({ message: "Sync complete", syncedCount, students: allStudents });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });
  
  app.get("/api/v1/teachers", async (req, res) => {
    res.json([]);
  });

  app.get("/api/v1/news", async (req, res) => {
    res.json([
      {
        id: '1', title: 'GES Announces New Curriculum Framework',
        content: 'The Ghana Education Service has released a comprehensive update to the basic school curriculum.',
        date: new Date().toISOString(), source: 'GES Official', url: '#'
      }
    ]);
  });
  
  app.get("/api/v1/academic-records", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.studentId) conditions.push(where("studentId", "==", q.studentId as string));
      if (q.academicYear) conditions.push(where("academicYear", "==", q.academicYear as string));
      if (q.academicTerm) conditions.push(where("academicTerm", "==", q.academicTerm as string));
      if (q.classLevel) conditions.push(where("classLevel", "==", q.classLevel as string));
      const snapshot = await getDocs(query(collection(getDb(), "academicRecords"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/v1/academic-records", async (req, res) => {
    try {
      const record = req.body;
      record.createdAt = new Date().toISOString();

      
      let existingId = record.id;
      if (!existingId) {
        // try to find existing
        const snapshot = await getDocs(query(collection(getDb(), "academicRecords"), 
          where("schoolId", "==", record.schoolId),
          where("studentId", "==", record.studentId),
          where("academicYear", "==", record.academicYear),
          where("academicTerm", "==", record.academicTerm)
        ));
        if (!snapshot.empty) {
          existingId = snapshot.docs[0].id;
        }
      }
      
      delete record.id;
      if (existingId) {
        await updateDoc(doc(getDb(), "academicRecords", existingId), record);
        res.status(200).json({ ...record, id: existingId });
      } else {
        const docRef = await addDoc(collection(getDb(), "academicRecords"), record);
        res.status(201).json({ ...record, id: docRef.id });
      }
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  // --- SUPERADMIN ---
  app.get("/api/v1/superadmin/schools", async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "schools"));
      const schools = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));
      
      const studentsSnapshot = await getDocs(collection(getDb(), "students"));
      const students = studentsSnapshot.docs.map(doc => doc.data());
      
      const schoolsWithCounts = schools.map(school => {
        const schoolStudents = students.filter(s => s.schoolId === school.id);
        const calcCount = schoolStudents.length > 0 ? schoolStudents.length : ((school as any).studentCount || 0);
        const paidCount = (school as any).paidStudentCount !== undefined && (school as any).paidStudentCount !== null ? Number((school as any).paidStudentCount) : 0;
        return {
          ...school,
          studentCount: calcCount,
          paidStudentCount: paidCount
        };
      });
      
      res.json(schoolsWithCounts);
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/superadmin/schools/:id/status", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), { status: req.body.status }, { merge: true });
      res.json({ message: "Status updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/superadmin/schools/:id/verify-payment", async (req, res) => {
    try {
      const paidCount = Number(req.body.paidStudentCount !== undefined ? req.body.paidStudentCount : 0);
      await setDoc(doc(getDb(), "schools", req.params.id), { 
        accessLevel: "Full", 
        paidStudentCount: paidCount, 
        billingNotice: "" 
      }, { merge: true });
      res.json({ message: "Payment verified", paidStudentCount: paidCount });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.put("/api/v1/superadmin/schools/:id/billing-notice", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), { billingNotice: req.body.billingNotice }, { merge: true });
      res.json({ message: "Notice sent" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.put("/api/v1/superadmin/schools/:id/access", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), { accessLevel: req.body.accessLevel }, { merge: true });
      res.json({ message: "Access updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
