
import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, doc, setDoc, addDoc, query, where, updateDoc, writeBatch, deleteDoc, getDoc } from "firebase/firestore/lite";
import fs from "fs";
import { GoogleGenAI } from "@google/genai";

let aiClient: any = null;
function getAiClient() {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;
    aiClient = new GoogleGenAI({
      apiKey: apiKey || "dummy_key",
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

// Safely load local config generated by AI Studio without breaking Vercel builds if the file is ignored
let db: any = null;

function getDb() {
  if (db) return db;

  let firebaseConfig: any = {};
  try {
    firebaseConfig = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'firebase-applet-config.json'), 'utf8'));
  } catch (e: any) {
    console.warn("Could not load local firebase config in api route.");
  }

  const finalConfig = {
    projectId: process.env.VITE_FIREBASE_PROJECT_ID || firebaseConfig.projectId || 'demo-project',
    appId: process.env.VITE_FIREBASE_APP_ID || firebaseConfig.appId || '1:1234567890:web:1234567890',
    apiKey: process.env.VITE_FIREBASE_API_KEY || firebaseConfig.apiKey || 'demo-api-key',
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfig.authDomain || 'demo-project.firebaseapp.com',
    firestoreDatabaseId: process.env.VITE_FIREBASE_DATABASE_ID || firebaseConfig.firestoreDatabaseId || '(default)',
  };

  const appFirebase = initializeApp(finalConfig);
  db = getFirestore(appFirebase, finalConfig.firestoreDatabaseId);
  return db;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Helper for checking dev environment api key
  const validateApiKey = (req, res, next) => {
    const authHeader = req.headers.authorization;
    if (authHeader && authHeader.startsWith('Bearer ')) {
      // In a real app we'd query db for the API key to find the schoolId
      // For now, we'll extract it assuming it's passed or default to dev
      req.schoolId = "dev-school";
      next();
    } else {
      res.status(401).json({ error: 'Unauthorized' });
    }
  };

  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

// --- GEMINI AI CENTER ENDPOINT ---
function generateSmartNaCCAChatResponse(query: string, level?: string, subject?: string, schoolName?: string) {
  const q = (query || "").toLowerCase();
  const school = schoolName || "Ghana Basic School";
  const lvl = level || "Basic School";
  const subj = subject || "General";

  if (q.includes("fraction") || q.includes("math") || q.includes("number") || q.includes("algebra") || q.includes("geometry") || q.includes("ratio")) {
    return `### NaCCA MATHEMATICS PEDAGOGICAL ADVICE
**TARGET LEVEL:** ${lvl} | **SUBJECT:** Mathematics | **SCHOOL:** ${school}
**QUERY:** "${query}"

---

#### 1. CORE NaCCA MATHEMATICS STRATEGY
Ghana's Standard-Based Curriculum emphasizes the **Concrete-Pictorial-Abstract (CPA)** approach for teaching mathematical concepts. Rather than starting with abstract formulas, begin with hands-on physical materials.

#### 2. PRACTICAL CLASSROOM STEP-BY-STEP ACTIVITY
1. **Concrete Phase (Hands-On):**
   - Use locally available Teaching and Learning Materials (TLMs) such as bottle caps, orange/papaya slices, grid paper, or wooden counters.
   - For fractions: Give learners an orange or paper circle and guide them to fold or cut it into equal parts (1/2, 1/4, 3/4).
2. **Pictorial Phase (Visual Representation):**
   - Draw fraction strips or shaded region diagrams on the blackboard.
   - Ask learners to shade equivalent regions in their square grid notebooks.
3. **Abstract Phase (Symbolic Notation):**
   - Introduce standard notation ($1/2$, $2/4$, $3/6$) and connect it directly to the physical equal parts observed.

#### 3. RECOMMENDED LOW-COST LOCAL TLMs
- **Counters:** Soda bottle caps (pito caps), palm kernel shells, polished river stones.
- **Fraction Strips:** Cut-out strips of cardboard from old carton boxes.
- **Geoboards:** Plywood boards with small nails and rubber bands for geometry/area.

#### 4. NaCCA CORE COMPETENCIES & ASSESSMENT
- **Critical Thinking & Problem Solving:** Pose real-world Ghana context problems (e.g., *"If Akosua shares 12 mangos equally among 3 friends, what fraction does each get?"*).
- **Classroom Formative Task:** Ask learners to create their own fraction diagrams using colored pencils and present to their group.`;
  }

  if (q.includes("science") || q.includes("cell") || q.includes("matter") || q.includes("plant") || q.includes("animal") || q.includes("energy") || q.includes("organ")) {
    return `### NaCCA INTEGRATED SCIENCE GUIDANCE
**TARGET LEVEL:** ${lvl} | **SUBJECT:** Integrated Science | **SCHOOL:** ${school}
**QUERY:** "${query}"

---

#### 1. INQUIRY-BASED SCIENCE METHODOLOGY
The NaCCA Science Curriculum focuses on practical scientific investigation, critical observation, and fostering curiosity about the natural environment in Ghana.

#### 2. STEP-BY-STEP INSTRUCTIONAL DELIVERABLE
1. **Engage (Warm-Up Hook):**
   - Bring realia (e.g. fresh leaves, onion bulbs, soil samples, or clean water containers) to class. Ask learners probing questions about what they observe with their senses.
2. **Explore (Small Group Investigation):**
   - Divide the class into mixed-ability cooperative groups of 4-5 learners.
   - Hand out magnifying glasses, plastic specimens, or charts. Assign roles: Leader, Reader, Recorder, Presenter.
3. **Explain (Learner Presentations):**
   - Groups share their observations on the blackboard. Correct misconceptions constructively.
4. **Elaborate & Extend:**
   - Link the scientific concept to daily life in Ghana (e.g., food preservation, environmental hygiene, renewable solar energy).

#### 3. RECOMMENDED LOCAL TLMs
- **Microscopy Alternative:** Water drop lenses on plastic strips or clear plastic magnifying lenses.
- **Specimens:** Local leaves, germinated maize/bean seeds, insect collections, soil samples (clay, sand, loam).
- **Safety Gear:** Clean reusable plastic gloves made from food bags.

#### 4. NaCCA CORE COMPETENCIES & ASSESSMENT
- **Cultural Identity & Environmental Awareness:** Discuss local conservation of water bodies and tree planting.
- **Assessment Task:** 5-minute exit ticket drawing task (e.g., *"Draw and label two key parts of the plant/cell observed today."*)`;
  }

  if (q.includes("ict") || q.includes("comput") || q.includes("code") || q.includes("tech") || q.includes("software") || q.includes("hardware")) {
    return `### NaCCA COMPUTING / ICT PEDAGOGY
**TARGET LEVEL:** ${lvl} | **SUBJECT:** Computing | **SCHOOL:** ${school}
**QUERY:** "${query}"

---

#### 1. UNPLUGGED & PRACTICAL ICT INSTRUCTION
When teaching Computing in schools with limited hardware, use **Unplugged Computer Science** strategies—teaching algorithmic thinking, hardware concepts, and logic using physical models and role-play.

#### 2. PRACTICAL CLASSROOM ACTIVITIES
1. **Hardware Identification:** Use cardboard cut-outs of keyboards, mice, system units, and monitors. Practice touch-typing finger positions on drawn cardboard keyboards.
2. **Algorithm & Flowchart Role-Play:** Teach steps in computing by asking learners to write algorithm instructions for "How to prepare tea" or "How to fetch water" on chart paper using decision symbols.
3. **Data & Information Sorting:** Use index cards or colored paper to demonstrate how computers store and sort numbers and text.

#### 3. RECOMMENDED TLMs
- **Cardboard Computer Models:** Student-made cardboard desktop computers with labeled ports.
- **Logic Cards:** Binary number cards made from cereal boxes.
- **Flowchart Posters:** Laminated wall charts showing standard ISO flowchart shapes (Oval, Rectangle, Diamond).

#### 4. ASSESSMENT & COMPETENCIES
- **Digital Literacy & Problem Solving:** Evaluate learners' ability to break down a complex task into sequential logical steps.`;
  }

  if (q.includes("discipline") || q.includes("behavior") || q.includes("class") || q.includes("manage") || q.includes("noise") || q.includes("large")) {
    return `### NaCCA POSITIVE CLASSROOM MANAGEMENT & DISCIPLINE
**TARGET LEVEL:** ${lvl} | **SCHOOL:** ${school}
**QUERY:** "${query}"

---

#### 1. POSITIVE BEHAVIOR SUPPORT (PBS) FRAMEWORK
Ghana Ministry of Education and NaCCA guidelines strictly promote positive non-corporal discipline that nurtures mutual respect, self-control, and emotional wellbeing.

#### 2. STRATEGIES FOR MANAGING LARGE GHANAIAN CLASSES (40+ LEARNERS)
1. **Establish Clear Co-Created Rules:** On Day 1, develop 4-5 key positive classroom rules WITH the learners (e.g. *"Raise hand to speak"*, *"Listen when others talk"*, *"Be kind and respectful"*). Post them prominently.
2. **Group Station Leaders:** Appoint responsible Group Leaders (rotating weekly) to manage group noise, distribute exercise books, and maintain order.
3. **Non-Verbal Signals:** Use clapping patterns, a small hand bell, or a call-and-response phrase (e.g., Teacher: *"Class, Attention!"* -> Learners: *"Eyes on Teacher!"*).
4. **Targeted Praise:** Publicly praise positive behavior rather than giving sole attention to disruptions.

#### 3. REMEDIAL & INCLUSIVE ACTION
- For persistently disruptive learners, assign specific classroom responsibilities (e.g. board wiper, TLM monitor) to channel their energy constructively.
- Engage parents respectfully through the PTA or informal consultation to understand home factors.`;
  }

  if (q.includes("read") || q.includes("english") || q.includes("phonic") || q.includes("letter") || q.includes("comprehen") || q.includes("grammar") || q.includes("twi") || q.includes("fante") || q.includes("ga") || q.includes("ewe")) {
    return `### NaCCA LANGUAGE & LITERACY PEDAGOGY
**TARGET LEVEL:** ${lvl} | **SUBJECT:** English / Ghanaian Languages | **SCHOOL:** ${school}
**QUERY:** "${query}"

---

#### 1. EARLY GRADE READING & CCP LANGUAGE STRATEGY
NaCCA literacy emphasizes systematic phonics instruction in early grades transitioning to critical comprehension, vocabulary development, and expressive writing in upper basic and JHS.

#### 2. PRACTICAL LITERACY LESSON STEPS
1. **Phonics & Blending (Warm-Up):** Use letter-sound flashcards. Guide learners to sound out phonemes ($/s/, /a/, /t/$) and blend them into words ($sat$).
2. **Shared Storytelling:** Read a culturally relevant story (e.g. Ananse tales, community heroes) with expressiveness. Pause to ask prediction questions (*"What do you think Ananse will do next?"*).
3. **Vocabulary Wall:** Write 3 new keywords on the classroom word wall daily. Have learners use them in original sentences.
4. **Group Guided Reading:** Group learners by reading levels to give targeted support.

#### 3. RECOMMENDED LOCAL TLMs
- **Phonics Flipcharts:** Made from Manila cards and marker pens.
- **Letter Cubes:** Wooden blocks or cardboard cubes with letters written on all faces.
- **Story Baskets:** Physical props related to the day's story topic.

#### 4. NaCCA CORE COMPETENCIES
- **Communication & Collaboration:** Pair-share reading activities where learners read aloud to a partner and provide friendly feedback.`;
  }

  return `### NaCCA TEACHER ASSISTANT EXPERT GUIDANCE
**TARGET LEVEL:** ${lvl} | **SUBJECT / FOCUS:** ${subj} | **SCHOOL:** ${school}
**TEACHER QUESTION:** "${query}"

---

#### 1. NaCCA CURRICULUM CONTEXT & PEDAGOGICAL STANDARD
In line with Ghana's Standard-Based Curriculum (SBC) and Common Core Programme (CCP), teaching must transition from traditional teacher-led lecturing to active, learner-centered, activity-based instruction.

#### 2. TAILORED ACTIONABLE RECOMMENDATIONS FOR YOUR QUESTION
1. **Core Instructional Strategy:**
   - Address **"${query}"** by structuring your lesson into three distinct phases: **Phase 1 (Starter Hook - 10 mins)**, **Phase 2 (Main Collaborative Investigation - 35 mins)**, and **Phase 3 (Plenary Reflection - 15 mins)**.
2. **Learner Engagement:**
   - Group learners into heterogeneous (mixed-ability) teams of 4-6. Give each team a specific role (Leader, Recorder, Resource Handler, Presenter).
3. **Differentiation & Inclusion:**
   - Provide visual aids and simplified task sheets for struggling learners, while challenging advanced learners with open-ended extension questions related to "${query}".

#### 3. PRACTICAL LOCAL TLMs (TEACHING & LEARNING MATERIALS)
- **Primary Visual Aids:** Wall charts, cardboard cut-outs, flashcards, or realia drawn from the local community environment.
- **Hands-On Manipulatives:** Bottle caps, counters, grid sheets, or local models.

#### 4. ASSESSMENT & NaCCA CORE COMPETENCIES
- **Formative Assessment:** Use rapid mini-whiteboards, exit tickets, or oral presentations to evaluate understanding during Phase 3.
- **Core Competencies Nurtured:** Critical Thinking & Problem Solving, Cultural Identity, Communication & Collaboration, Personal Development.`;
}

function generateDynamicLessonPlan(schoolName: string, params: any) {
  const { level, subject, strand, subStrand, contentStandard, indicator, topic, duration, classSize, tlms } = params || {};
  const t = topic || "Key Curriculum Concept";
  const subj = subject || "Integrated Science";
  const lvl = level || "Basic 7 (JHS 1)";

  return `### NaCCA STANDARD-BASED LESSON PLAN
**SCHOOL:** ${schoolName || "Ghana Basic School"}
**CLASS/LEVEL:** ${lvl} | **SUBJECT:** ${subj}
**DURATION:** ${duration || "60 Mins"} | **CLASS SIZE:** ${classSize || "45 Learners"}
**STRAND:** ${strand || "Core Subject Strand"}
**SUB-STRAND:** ${subStrand || "Curriculum Sub-Strand"}
**CONTENT STANDARD:** ${contentStandard || "CS.1.1"}
**PERFORMANCE INDICATOR:** ${indicator || "IND.1.1.1 - Demonstrate understanding of " + t}
**CORE COMPETENCIES:** Critical Thinking & Problem Solving, Communication & Collaboration, Cultural Identity.
**TLMs:** ${tlms || "Subject charts, realia, local community specimens, group activity sheets."}

---

#### PHASE 1: STARTER / WARM-UP (10 MINS)
1. **Prior Knowledge Check:** Ask learners probing diagnostic questions about their real-life experiences with **${t}**.
2. **Engaging Hook Activity:** Show a relevant local specimen, realia, or chart related to **${t}**. Ask learners to share what they observe.
3. **Learning Target Statement:** By the end of this lesson, learners will be able to explain, demonstrate, and apply key concepts of **${t}** in ${subj}.

#### PHASE 2: MAIN / TEACHING & LEARNING ACTIVITIES (35 MINS)
1. **Step 1 (Teacher Demonstration & Concept Unpacking):**
   - Introduce the core terms and principles of **${t}**. Use clear illustrations on the board and connect to the local Ghanaian context.
2. **Step 2 (Cooperative Group Investigation):**
   - Divide learners into mixed-gender groups of 4-5.
   - Hand out activity cards and TLMs (${tlms || "worksheets and charts"}).
   - Task: Guide groups to investigate, discuss, and record key features of **${t}**.
3. **Step 3 (Group Presentations & Peer Review):**
   - Call upon group rapporteurs to present findings. Facilitate class discussion, clarifying misconceptions and encouraging positive feedback.
4. **Step 4 (Differentiation & Inclusion):**
   - Provide tactile/visual reinforcement for learners who need extra support. Offer challenge questions on **${t}** for fast finishers.

#### PHASE 3: PLENARY / REFLECTION & ASSESSMENT (15 MINS)
1. **Summary Review:** Conduct a 3-minute rapid recap of main key takeaways regarding **${t}**.
2. **Formative Evaluation Task:**
   - Question 1: Explain the main purpose of **${t}** in ${subj}.
   - Question 2: Give two practical examples of how **${t}** applies in daily Ghanaian life.
3. **Homework / Home Project:** Write a 1-page summary in exercise books or prepare a small poster illustrating **${t}**.`;
}

function generateDynamicSOL(schoolName: string, params: any) {
  const { level, subject, term, totalWeeks } = params || {};
  const subj = subject || "Mathematics";
  const lvl = level || "Basic 8 (JHS 2)";
  const tNum = term || "1";
  const weeks = parseInt(totalWeeks || "12", 10) || 12;

  const topicList = [
    `Introduction to ${subj} Concepts`, `Core Strand 1 Fundamentals`, `Sub-strand 1 Application`,
    `Practical Group Investigation`, `Intermediate Skills Building`, `Mid-Term Evaluation & Review`,
    `Core Strand 2 In-depth Study`, `Advanced Problem Solving`, `Real-world Applications in Ghana`,
    `BECE / Terminal Exam Revision`, `Terminal Examinations`, `Report Cards & Parents Conference`
  ];

  let rows = "";
  for (let w = 1; w <= weeks; w++) {
    const top = topicList[(w - 1) % topicList.length];
    const code = `B${lvl.replace(/[^0-9]/g, '') || '8'}.${(w % 4) + 1}.1.${(w % 3) + 1}`;
    rows += `| **Week ${w}** | Strand ${(w % 3) + 1} | ${code} | ${top} | Charts, Realia, Worksheets | Formative Quiz ${w} |\n`;
  }

  return `### NaCCA SCHEME OF LEARNING (SOL)
**SCHOOL:** ${schoolName || "Ghana Basic School"}
**CLASS/LEVEL:** ${lvl} | **SUBJECT:** ${subj}
**ACADEMIC TERM:** Term ${tNum} | **DURATION:** ${weeks} Weeks

| Week | Strand & Sub-strand | Content Standard Code | Topic / Focus Area | Key TLMs | Assessment Method |
| --- | --- | --- | --- | --- | --- |
${rows}`;
}

function generateDynamicExam(schoolName: string, params: any) {
  const { level, subject, topic, mcqCount, theoryCount, difficulty, includeAnswers } = params || {};
  const subj = subject || "Social Studies";
  const lvl = level || "Basic 9 (JHS 3)";
  const top = topic || "Comprehensive Term Work";
  const mcqs = parseInt(mcqCount || "5", 10) || 5;
  const theory = parseInt(theoryCount || "2", 10) || 2;
  const diff = difficulty || "BECE Standard";

  return `### ${schoolName ? schoolName.toUpperCase() : "GHANA BASIC SCHOOL"}
**TERMINAL EXAMINATION - ACADEMIC EVALUATION**
**SUBJECT:** ${subj} | **CLASS:** ${lvl}
**TIME ALLOWED:** 1 HOUR 30 MINUTES | **DIFFICULTY:** ${diff}
**EXAM TOPIC / SCOPE:** ${top}

---

#### SECTION A: MULTIPLE CHOICE QUESTIONS (Answer ALL questions - ${mcqs} Questions)

1. In the study of ${subj}, which of the following best defines the key concept of **${top}**?
   A) A temporary emergency measure  B) A fundamental structured subject topic  C) An optional extracurricular activity  D) A historical event from 1957

2. Which of the following is considered a primary requirement when analyzing **${top}** in Ghana?
   A) Ignoring local community needs  B) Applying systematic problem-solving and critical thinking  C) Promoting conflict among groups  D) Relying solely on memory without understanding

3. When applying concepts of ${subj} to real-life situations in Ghanaian communities, learners should prioritize:
   A) Sustainable development and civic responsibility  B) Destruction of natural resources  C) Disregarding national laws  D) Excessive expenditure

4. Which institution or body plays a vital role in supervising educational standards and assessment for ${subj} in Ghana?
   A) NaCCA & WAEC  B) GFA  C) Ghana Post  D) VRA

5. An effective way to resolve challenges associated with **${top}** in Ghanaian schools is through:
   A) Collaborative dialogue and positive stakeholder engagement  B) Abandoning school projects  C) Canceling all assessments  D) Ignoring feedback

---

#### SECTION B: STRUCTURED & ESSAY QUESTIONS (Answer ALL questions)

**QUESTION 1**
a) Define **${top}** as studied in ${subj} at the ${lvl} level. *(4 marks)*
b) Explain **three** reasons why understanding **${top}** is important for national development in Ghana. *(6 marks)*

**QUESTION 2**
a) State **two** major challenges encountered when implementing concepts of **${top}** in local communities. *(4 marks)*
b) Suggest **three** practical solutions that students and community leaders can adopt to address these challenges. *(6 marks)*

${includeAnswers ? `---

#### TEACHER'S MARKING SCHEME & MODEL ANSWERS

**SECTION A ANSWERS:**
1. B (Fundamental structured topic) | 2. B (Systematic problem-solving) | 3. A (Sustainable development) | 4. A (NaCCA & WAEC) | 5. A (Collaborative dialogue)

**SECTION B MODEL ANSWERS:**
- **Q1a:** ${top} in ${subj} refers to the systematic study and application of core principles within the NaCCA curriculum framework.
- **Q1b:** 1) Promotes critical thinking and civic literacy. 2) Encourages practical problem solving in local Ghanaian communities. 3) Prepares learners for WAEC/BECE national examinations.
- **Q2b:** Solutions include community sensitization, resource mobilization, and active student participation in project work.` : ''}`;
}

function generateDynamicRemarks(schoolName: string, params: any) {
  const { studentName, level, gender, score, attendance, conduct, competencies } = params || {};
  const sName = studentName || "Kwame Boateng";
  const g = gender === 'Female' ? 'Female' : 'Male';
  const pron = g === 'Female' ? 'She' : 'He';
  const pos = g === 'Female' ? 'Her' : 'His';
  const lvl = level || "Basic 7";

  return `### TERMINAL REPORT REMARKS & PARENT ADVICE
**LEARNER NAME:** ${sName} | **GENDER:** ${g}
**CLASS/LEVEL:** ${lvl} | **OVERALL PERFORMANCE:** ${score || "85% (Grade A - Distinction)"}
**ATTENDANCE & PUNCTUALITY:** ${attendance || "58/60 Days"} | **CONDUCT:** ${conduct || "Polite, disciplined, cooperative"}
**OBSERVED COMPETENCIES:** ${competencies || "Strong logical reasoning, active team player"}

---

#### 1. CLASS TEACHER'S REMARK
${sName} is an exceptional, disciplined, and focused learner in ${lvl}. ${pron} consistently displays a genuine passion for academic work and active participation during class discussions. ${pos} performance of ${score || "85%"} reflects diligent study habits and high intellectual promise. With continued guidance and encouragement, ${pron.toLowerCase()} will reach even greater academic heights.

#### 2. HEADTEACHER'S ENDORSEMENT
A commendable terminal record. ${sName} is congratulated on maintaining high academic standards and exemplary character throughout the term. Keep striving for excellence!

#### 3. TAILORED ADVICE TO PARENTS / GUARDIANS
1. **Home Learning Schedule:** Maintain a daily 2-hour structured home revision and reading routine for ${sName}.
2. **Nurturing Talents:** Encourage ${sName} to engage in STEM/Science and debate club activities to build upon observed strengths in ${competencies || "logical reasoning and leadership"}.
3. **Administrative Note:** Please ensure all necessary learning materials, textbooks, and school fees are prepared promptly prior to school reopening.`;
}

function generateDynamicCircular(schoolName: string, params: any) {
  const { purpose, keyDates, venue, feeOrDetails } = params || {};
  const sName = schoolName || "Ghana Educational Complex";
  const p = purpose || "End of Term Vacation & PTA General Assembly";

  return `### ${sName.toUpperCase()}
**OFFICIAL CIRCULAR TO PARENTS & GUARDIANS**
**DATE:** ${new Date().toLocaleDateString('en-GB')} | **REF:** GEC/CIRC/${new Date().getFullYear()}/05

**SUBJECT:** ${p}

Dear Parents & Guardians,

On behalf of the Management and Teaching Staff of ${sName}, we present our warm compliments and sincere gratitude for your continued partnership in raising standard-bearing learners.

As we bring the current academic term to a successful close, please take careful note of the following important arrangements:

1. **VACATION & REOPENING TIMELINE:**
   - ${keyDates || "Vacation Date: Friday, 12th April | Reopening Date: Tuesday, 6th May"}

2. **PARENTS-TEACHERS ASSOCIATION (PTA) MEETING:**
   - **Venue:** ${venue || "School Main Assembly Hall"}
   - All parents and guardians are cordially invited to attend as crucial decisions regarding learner welfare and academic programs will be finalized.

3. **FINANCIAL OBLIGATIONS & SCHOOL FEES:**
   - ${feeOrDetails || "School fees for the upcoming academic term must be paid into the school's official bank account or Mobile Money merchant line before reopening."}

We wish all our learners a safe, peaceful, and productive vacation.

Yours faithfully,

_______________________
**Headteacher / Management**
${sName}`;
}

function generateFallbackNaCCADoc(type: string, schoolName: string, params: any) {
  if (type === 'lesson-plan') return generateDynamicLessonPlan(schoolName, params);
  if (type === 'scheme-of-learning') return generateDynamicSOL(schoolName, params);
  if (type === 'exam-paper') return generateDynamicExam(schoolName, params);
  if (type === 'remarks') return generateDynamicRemarks(schoolName, params);
  if (type === 'circular') return generateDynamicCircular(schoolName, params);
  if (type === 'chat') return generateSmartNaCCAChatResponse(params?.query, params?.level, params?.subject, schoolName);
  return generateSmartNaCCAChatResponse(params?.query || "General curriculum guidance", params?.level, params?.subject, schoolName);
}

  app.post(["/api/v1/ai/generate", "/api/ai/generate"], async (req: any, res: any) => {
    try {
      const { type, schoolName, params } = req.body || {};
      const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;

      if (apiKey) {
        try {
          const ai = getAiClient();
          const systemInstruction = "You are an expert Ghanaian Education Specialist, Curriculum Developer, and NaCCA (National Council for Curriculum and Assessment) Lead Consultant. You specialize in Ghana's Standard-Based Curriculum (SBC) for Kindergarten & Primary schools, and Common Core Programme (CCP) for Junior High Schools (JHS 1-3). Your outputs are professional, accurate, culturally contextualized for Ghana, and immediately usable by Ghanaian teachers and school leaders.";

          let prompt = "";

          if (type === 'lesson-plan') {
            const { level, subject, strand, subStrand, contentStandard, indicator, topic, duration, classSize, tlms } = params || {};
            prompt = `Generate a comprehensive, ready-to-use NaCCA Lesson Plan in standard Ghanaian school format:
School Name: ${schoolName || "Ghana Basic School"}
Class/Level: ${level || "Basic 7 (JHS 1)"}
Subject: ${subject || "Integrated Science"}
Strand: ${strand || "Diversity of Matter"}
Sub-strand: ${subStrand || "Living and Non-Living Things"}
Content Standard: ${contentStandard || "B7.1.1.1"}
Indicator / Code: ${indicator || "B7.1.1.1.1"}
Topic / Lesson Title: ${topic || "Cells as Basic Units of Life"}
Duration: ${duration || "60 mins"}
Class Size: ${classSize || "45 learners"}
TLMs (Teaching Materials): ${tlms || "Microscope diagrams, charts of plant and animal cells, onion skin slides, realia"}

Format output with clean markdown headers and bullet points:
1. HEADER DETAILS (Class, Subject, Duration, Strand, Sub-strand, Content Standard, Performance Indicator, Core Competencies e.g. Critical Thinking & Problem Solving, Key Words, TLMs)
2. PHASE 1: STARTER / WARM-UP (5-10 mins) - Prior knowledge check, engaging hook, learning target statement.
3. PHASE 2: MAIN / TEACHING & LEARNING ACTIVITIES (30-40 mins) - Detailed Step 1, Step 2, Step 3, Step 4 with teacher actions, learner activities, group work, and differentiation for diverse learners.
4. PHASE 3: PLENARY / REFLECTION & ASSESSMENT (5-10 mins) - Summary review questions, self-reflection, and Homework/Project work.`;
          } else if (type === 'scheme-of-learning') {
            const { level, subject, term, totalWeeks } = params || {};
            prompt = `Generate a detailed NaCCA Scheme of Learning (SOL) for Ghana Schools:
Class/Level: ${level || "Basic 8 (JHS 2)"}
Subject: ${subject || "Mathematics"}
Term: Term ${term || "1"}
Total Weeks: ${totalWeeks || 12} Weeks

Produce a week-by-week table/breakdown covering all ${totalWeeks || 12} weeks in Term ${term || 1}. For each week include:
- Week Number
- Strand & Sub-strand
- Content Standard Code & Indicator
- Topic / Focus
- Recommended Resources / TLMs
- Core Competencies Developed
- Assessment Method`;
          } else if (type === 'exam-paper') {
            const { level, subject, topic, mcqCount, theoryCount, difficulty, includeAnswers } = params || {};
            prompt = `Create a complete Terminal Examination / Assessment Test Paper adhering to Ghanaian NaCCA & WAEC/BECE standards:
School: ${schoolName || "Basic School"}
Class/Level: ${level || "Basic 9 (JHS 3)"}
Subject: ${subject || "Social Studies"}
Topic / Scope: ${topic || "Comprehensive Term Work / BECE Revision"}
Difficulty Level: ${difficulty || "BECE Standard"}
Number of MCQs (Section A): ${mcqCount || 10}
Number of Structured/Theory Questions (Section B): ${theoryCount || 3}
Include Marking Scheme: ${includeAnswers ? "YES" : "NO"}

Format cleanly with:
- School Exam Header (Title, Subject, Class, Time Allowed: e.g. 1 Hour 30 Mins, Total Marks)
- SECTION A: MULTIPLE CHOICE QUESTIONS (1-${mcqCount || 10} with options A, B, C, D)
- SECTION B: STRUCTURED & THEORY QUESTIONS (Questions 1-${theoryCount || 3} with sub-parts e.g. 1a, 1b, 2a...)
${includeAnswers ? "- TEACHER'S MARKING SCHEME & MODEL ANSWERS (Clearly separated at the end with point allocation)" : ""}`;
          } else if (type === 'remarks') {
            const { studentName, level, gender, score, attendance, conduct, competencies } = params || {};
            prompt = `Generate personalized, encouraging, and actionable Terminal Report Remarks & Advice to Parents for a Ghanaian learner:
Student Name: ${studentName || "Kwame Mensah"}
Gender: ${gender || "Learner"}
Class/Level: ${level || "Basic 6"}
Overall Score/Grade: ${score || "84% (Grade A - Excellent)"}
Attendance & Punctuality: ${attendance || "58/60 days - Regular and Punctual"}
Conduct/Attitude: ${conduct || "Polite, well-behaved, active in class"}
Observed Competencies/Traits: ${competencies || "Strong logical reasoning, cooperative team player"}

Provide:
1. CLASS TEACHER'S REMARK (3-4 sentences highlighting academic performance, character, and areas for growth)
2. HEADTEACHER'S ENDORSEMENT REMARK (2 concise formal sentences)
3. TAILORED ADVICE TO PARENTS / GUARDIANS (3 actionable recommendations for supporting the child at home, e.g. establishing evening reading hours, monitoring homework, encouraging participation in science clubs, ensuring fee payment prior to reopening)`;
          } else if (type === 'circular') {
            const { purpose, keyDates, venue, feeOrDetails } = params || {};
            prompt = `Draft an official School Circular / Notice to Parents for a Ghanaian school:
School Name: ${schoolName || "Ghana Educational Complex"}
Purpose / Topic: ${purpose || "End of Term Vacation & Reopening Announcement"}
Key Dates: ${keyDates || "Vacation: 15th August, Reopening: 10th September"}
Venue / Location: ${venue || "School Main Assembly Hall"}
Additional Details / Fees: ${feeOrDetails || "Next Term School Fees: GHS 850 payable via Mobile Money or Bank Deposit"}

Write a polite, formal letter addressed to "Dear Parents & Guardians", signed by the Headteacher, structured with formal Ghanaian administrative tone, clear headings, bullet points for key dates/requirements, and warm closing phrases.`;
          } else if (type === 'chat') {
            const { query, level, subject, history } = params || {};
            let historyText = "";
            if (Array.isArray(history) && history.length > 0) {
              const recent = history.slice(-8);
              historyText = "PREVIOUS CONVERSATION CONTEXT:\n" + recent.map((m: any) => `${m.sender === 'user' ? 'Teacher/User' : 'NaCCA AI Assistant'}: ${m.text}`).join("\n") + "\n\n";
            }
            prompt = `${historyText}School: ${schoolName || "Ghana Basic School"}
Target Level/Class: ${level || "General Basic Education"}
Subject: ${subject || "General"}

Teacher Question / Prompt: "${query}"

As an expert Ghanaian NaCCA Curriculum Specialist & Master AI Assistant, answer the teacher's request directly, dynamically, and insightfully. Address whatever they ask — whether it is a curriculum question, lesson concept, translation, test questions, administrative letter draft, classroom problem, or creative idea. Use clear, beautifully formatted Markdown with bolding, lists, and headers where appropriate.`;
          } else {
            return res.status(400).json({ error: "Invalid type requested" });
          }

          const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
              systemInstruction,
              temperature: 0.7,
            }
          });

          if (response && response.text) {
            console.log(`[AI SUCCESS] Real-time Gemini 2.5 response generated for type: ${type}`);
            return res.json({ result: response.text });
          }
        } catch (apiErr: any) {
          console.error("Gemini API call error:", apiErr?.message || apiErr);
        }
      }

      // Fallback if no GEMINI_API_KEY or if API call encountered error
      const fallbackResult = generateFallbackNaCCADoc(type, schoolName, params);
      return res.json({ result: fallbackResult });
    } catch (err: any) {
      console.error("Gemini AI error:", err);
      res.status(500).json({ error: err?.message || "Failed to generate AI content" });
    }
  });

  // --- SCHOOLS ---
  app.get("/api/v1/schools", async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "schools"));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/schools", async (req, res) => {
    try {
      const { name, region, district, email, password } = req.body;
      const school = {
        name, region, district, email,
        status: "Active", accessLevel: "Full",
        userId: "admin-id", // mock
        createdAt: new Date().toISOString()
      };
      const docRef = await addDoc(collection(getDb(), "schools"), school);
      res.status(201).json({ ...school, id: docRef.id });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.get("/api/v1/schools/:id", async (req, res) => {
    try {
      const docRef = doc(getDb(), "schools", req.params.id);
      const snapshot = await getDoc(docRef);
      if (snapshot.exists()) {
        res.json({ ...snapshot.data(), id: snapshot.id });
      } else {
        res.status(404).json({ error: "School not found" });
      }
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/schools/:id", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), req.body, { merge: true });
      const docSnap = await getDoc(doc(getDb(), "schools", req.params.id));
      if (docSnap.exists()) {
        res.json({ ...docSnap.data(), id: docSnap.id });
      } else {
        res.json({ ...req.body, id: req.params.id });
      }
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- AUTH ---
  app.post("/api/v1/auth/login", async (req, res) => {
    try {
      const { email, password, role } = req.body;
      if (!email || !password) {
        return res.status(400).json({ error: "Email and password are required." });
      }

      const cleanEmail = email.trim().toLowerCase();
      const rawEmail = email.trim();

      if (cleanEmail === "superadmin@ges.gov.gh") {
        return res.json({
          success: true,
          user: { email: cleanEmail, fullName: "Super Admin", role: "SuperAdmin" },
          school: {
            id: 'superadmin-ges',
            name: 'GES Super Admin Console',
            slug: 'ges-super-admin',
            region: 'National',
            district: 'HQ',
            email: 'superadmin@ges.gov.gh',
            status: 'Active',
            accessLevel: 'Full',
            createdAt: new Date().toISOString()
          },
          role: "SuperAdmin"
        });
      }

      // 1. Check Teachers collection first
      let teacherSnap = await getDocs(query(collection(getDb(), "teachers"), where("email", "==", cleanEmail)));
      if (teacherSnap.empty) {
        teacherSnap = await getDocs(query(collection(getDb(), "teachers"), where("email", "==", rawEmail)));
      }

      if (!teacherSnap.empty) {
        const teacherDoc = teacherSnap.docs[0];
        const teacherData = teacherDoc.data();
        const storedPassword = teacherData.password || teacherData.initialPassword;

        if (storedPassword !== password) {
          return res.status(401).json({ error: "Invalid password for teacher account." });
        }

        const schoolDocSnap = await getDoc(doc(getDb(), "schools", teacherData.schoolId));
        if (!schoolDocSnap.exists()) {
          return res.status(404).json({ error: "Associated school account not found." });
        }

        const schoolData = schoolDocSnap.data();
        if (schoolData.status === 'Deactivated') {
          return res.status(401).json({ error: "Your school account has been deactivated. Please contact the administrator." });
        }

        return res.json({
          success: true,
          role: "Teacher",
          user: { email: teacherData.email, fullName: teacherData.fullName, role: "Teacher" },
          teacher: { ...teacherData, id: teacherDoc.id },
          school: { ...schoolData, id: schoolDocSnap.id }
        });
      }

      // 2. Check Schools collection for Admin accounts
      let schoolSnap = await getDocs(query(collection(getDb(), "schools"), where("email", "==", cleanEmail)));
      if (schoolSnap.empty) {
        schoolSnap = await getDocs(query(collection(getDb(), "schools"), where("email", "==", rawEmail)));
      }

      if (schoolSnap.empty) {
        return res.status(401).json({ error: "Invalid official school email or password." });
      }

      const schoolDoc = schoolSnap.docs[0];
      const schoolData = schoolDoc.data();
      if (schoolData.status === 'Deactivated') {
        return res.status(401).json({ error: "Your school account has been deactivated. Please contact the administrator." });
      }

      return res.json({
        success: true,
        role: role || "Admin",
        user: { email: schoolData.email || rawEmail, fullName: "Admin User", role: role || "Admin" },
        school: { ...schoolData, id: schoolDoc.id }
      });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });


  // --- STUDENTS ---
  app.get("/api/v1/students", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "students"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/students/:id", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "students", req.params.id), req.body);
      const docSnap = await getDoc(doc(getDb(), "students", req.params.id));
      if (docSnap.exists()) {
        res.json({ ...docSnap.data(), id: docSnap.id });
      } else {
        res.json({ ...req.body, id: req.params.id });
      }
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/students/:id/academic", async (req, res) => {
    try {
      const studentRef = doc(getDb(), "students", req.params.id);
      await updateDoc(studentRef, req.body);
      const updatedSnap = await getDoc(studentRef);
      if (updatedSnap.exists()) {
        res.json({ ...updatedSnap.data(), id: updatedSnap.id });
      } else {
        res.status(404).json({ error: "Student not found" });
      }
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.delete("/api/v1/students/:id", async (req, res) => {
    try {

      
      const docRef = doc(getDb(), "students", req.params.id);
      const docSnap = await getDoc(docRef);
      if (docSnap.exists()) {
        const student = docSnap.data();
        await deleteDoc(docRef);
        
        if (student.schoolId) {
          const schoolRef = doc(getDb(), "schools", student.schoolId);
          const schoolSnap = await getDoc(schoolRef);
          if (schoolSnap.exists()) {
            const currentCount = schoolSnap.data().studentCount || 0;
            await updateDoc(schoolRef, { studentCount: Math.max(0, currentCount - 1) });
          }
        }
      }
      
      res.json({ message: "Student deleted" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students", async (req, res) => {
    try {
      const student = req.body;
      student.createdAt = new Date().toISOString();

      if (!student.admissionNo || student.admissionNo === "PENDING-SYNC") {
        student.admissionNo = `ADM-${Math.floor(Math.random() * 1000000).toString().padStart(6, '0')}`;
      }
      delete student.id;
      const docRef = await addDoc(collection(getDb(), "students"), student);
      
      // Update school student count
      if (student.schoolId) {
        const schoolRef = doc(getDb(), "schools", student.schoolId);
        const schoolSnap = await getDoc(schoolRef);
        if (schoolSnap.exists()) {
          const currentCount = schoolSnap.data().studentCount || 0;
          await updateDoc(schoolRef, { studentCount: currentCount + 1 });
        }
      }
      
      res.status(201).json({ ...student, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students/bulk", async (req, res) => {
    try {
      const { schoolId, students } = req.body;
      if (!Array.isArray(students) || students.length === 0) {
        return res.status(400).json({ error: "No student records provided for bulk upload." });
      }

      const batch = writeBatch(getDb());
      const results = [];
      for (const s of students) {
        const docRef = doc(collection(getDb(), "students"));
        const targetSchoolId = s.schoolId || schoolId;
        const studentObj = {
          schoolId: targetSchoolId,
          admissionNo: s.admissionNo || s['Admission No'] || `ADM-${Math.floor(100000 + Math.random() * 900000)}`,
          fullName: s.fullName || s['Full Name'] || 'Unknown Student',
          dob: s.dob || s['Date of Birth'] || '2010-01-01',
          gender: s.gender || s['Gender'] || 'Male',
          classLevel: s.classLevel || s['Class Level'] || 'Basic 1',
          boardingStatus: s.boardingStatus || s['Boarding Status'] || 'Day',
          guardianName: s.guardianName || s['Guardian Name'] || 'N/A',
          guardianPhone: s.guardianPhone || s['Guardian Phone'] || 'N/A',
          passportPicture: s.passportPicture || '',
          admissionStatus: s.admissionStatus || 'Admitted',
          feePaid: Number(s.feePaid) || 0,
          feeTotal: Number(s.feeTotal || s['Fee Total']) || (s.boardingStatus === 'Boarding' || s['Boarding Status'] === 'Boarding' ? 2500 : 1200),
          paymentStatus: s.paymentStatus || ((Number(s.feePaid) || 0) >= (Number(s.feeTotal) || 1200) ? 'Paid' : (Number(s.feePaid) || 0) > 0 ? 'Partial' : 'Unpaid'),
          syncStatus: 'synced',
          remarks: s.remarks || s['Remarks'] || '',
          createdAt: s.createdAt || new Date().toISOString()
        };

        batch.set(docRef, studentObj);
        results.push({ ...studentObj, id: docRef.id });
      }
      await batch.commit();
      
      // Update school student count
      const targetSchoolId = schoolId || (results.length > 0 && results[0].schoolId);
      if (targetSchoolId) {
        const schoolRef = doc(getDb(), "schools", targetSchoolId);
        const schoolSnap = await getDoc(schoolRef);
        if (schoolSnap.exists()) {
          const currentCount = schoolSnap.data().studentCount || 0;
          await updateDoc(schoolRef, { studentCount: currentCount + results.length });
        }
      }
      
      res.status(201).json(results);
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students/promote", async (req, res) => {
    try {
      const { studentIds, targetClass } = req.body;
      const batch = writeBatch(getDb());
      for (const id of studentIds) {
        batch.update(doc(getDb(), "students", id), { classLevel: targetClass });
      }
      await batch.commit();
      res.json({ message: "Promoted successfully" });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.get("/api/v1/sis/students", validateApiKey, async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "students"));
      res.json({ data: snapshot.docs.map(d => ({ ...d.data(), id: d.id })) });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  // --- PAYMENTS ---
  app.get("/api/v1/payments", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.studentId) conditions.push(where("studentId", "==", q.studentId as string));
      const snapshot = await getDocs(query(collection(getDb(), "payments"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/payments", async (req, res) => {
    try {
      const payment = req.body;
      payment.timestamp = new Date().toISOString();

      const docRef = await addDoc(collection(getDb(), "payments"), payment);
      res.status(201).json({ ...payment, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- BACKUPS ---
  app.get("/api/v1/backups", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "backupLogs"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/backups", async (req, res) => {
    try {
      const { schoolId, type } = req.body;
      const log = {
        schoolId, type: type || "Manual", timestamp: new Date().toISOString(),
        recordsCount: 0, fileName: `backup_${schoolId}_${Date.now()}.json`, status: "Completed"
      };
      const docRef = await addDoc(collection(getDb(), "backupLogs"), log);
      res.status(201).json({ log: { ...log, id: docRef.id } });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- API KEYS ---
  app.get("/api/v1/api-keys", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "apiKeys"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/api-keys", async (req, res) => {
    try {
      const { schoolId, name } = req.body;
      const key = {
        schoolId, name, status: "Active",
        token: `geda_tok_${Math.random().toString(36).substr(2, 9)}`,
        createdAt: new Date().toISOString()
      };
      const docRef = await addDoc(collection(getDb(), "apiKeys"), key);
      res.status(201).json({ ...key, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/api-keys/revoke", async (req, res) => {
    try {
      const { keyId } = req.body;
      if (keyId.startsWith("demo-key-")) return res.json({ message: "Revoked" });
      await updateDoc(doc(getDb(), "apiKeys", keyId), { status: "Revoked" });
      res.json({ message: "Revoked" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- OTHERS ---
  app.get("/api/v1/attendance", async (req, res) => {
    try {
      const q: any = req.query;
      const schoolId = (q.schoolId as string) || "";
      if (!schoolId) {
        return res.json([]);
      }

      const snapshot = await getDocs(query(collection(getDb(), "attendance"), where("schoolId", "==", schoolId)));
      let records = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));

      if (q.date) {
        records = records.filter((r: any) => r.date === q.date);
      }
      if (q.studentId) {
        records = records.filter((r: any) => r.studentId === q.studentId);
      }
      if (q.academicYear) {
        records = records.filter((r: any) => r.academicYear === q.academicYear);
      }
      if (q.academicTerm) {
        records = records.filter((r: any) => r.academicTerm === q.academicTerm);
      }

      res.json(records);
    } catch (e: any) {
      console.error("Error fetching attendance:", e);
      res.status(500).json({ error: e.message || "Failed to fetch attendance" });
    }
  });

  app.post("/api/v1/attendance/batch", async (req, res) => {
    try {
      const { schoolId, records } = req.body;
      if (!schoolId || !Array.isArray(records) || records.length === 0) {
        return res.json({ message: "No attendance records to save" });
      }

      const batch = writeBatch(getDb());
      for (const r of records) {
        // Enforce deterministic ID based on student and date to prevent duplicate document entries
        const docId = r.id || `${r.studentId}_${r.date}`;
        const docRef = doc(getDb(), "attendance", docId);
        const recordData = {
          ...r,
          id: docId,
          schoolId: schoolId || r.schoolId,
          updatedAt: new Date().toISOString()
        };
        batch.set(docRef, recordData, { merge: true });
      }
      await batch.commit();
      res.json({ message: "Attendance marked successfully" });
    } catch (e: any) {
      console.error("Error saving attendance batch:", e);
      res.status(500).json({ error: e.message || "Failed to save attendance" });
    }
  });

  app.post("/api/v1/sync", async (req, res) => {
    try {
      const { schoolId, students } = req.body;
      let syncedCount = 0;

      const batch = writeBatch(getDb());
      for (const s of students) {
        const docRef = doc(collection(getDb(), "students"));
        s.createdAt = s.createdAt || new Date().toISOString();
        s.syncStatus = "synced";
        delete s.id; // Remove offline ID
        batch.set(docRef, s);
        syncedCount++;
      }
      if (syncedCount > 0) {
        await batch.commit();
      }
      
      const snapshot = await getDocs(query(collection(getDb(), "students"), where("schoolId", "==", schoolId || "")));
      const allStudents = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));
      
      res.json({ message: "Sync complete", syncedCount, students: allStudents });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });
  
  app.get("/api/v1/teachers", async (req, res) => {
    try {
      const { schoolId } = req.query;
      if (!schoolId) {
        return res.status(400).json({ error: "schoolId is required" });
      }
      const snapshot = await getDocs(query(collection(getDb(), "teachers"), where("schoolId", "==", schoolId as string)));
      const teachers = snapshot.docs.map(d => ({ ...d.data(), id: d.id }));
      res.json(teachers);
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/v1/teachers", async (req, res) => {
    try {
      const { schoolId, fullName, email, password, department, subject, isClassTeacher, assignedClass } = req.body;
      if (!schoolId || !fullName || !email || !password || !department) {
        return res.status(400).json({ error: "Missing required teacher registration fields." });
      }
      const cleanEmail = email.trim().toLowerCase();
      const teacherData = {
        schoolId,
        fullName,
        email: cleanEmail,
        password,
        initialPassword: password,
        department,
        subject: subject || 'General',
        isClassTeacher: Boolean(isClassTeacher),
        assignedClass: assignedClass || null,
        createdAt: new Date().toISOString()
      };
      const docRef = await addDoc(collection(getDb(), "teachers"), teacherData);
      res.status(201).json({ ...teacherData, id: docRef.id });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/v1/teachers/reset-password", async (req, res) => {
    try {
      const { teacherId, newPassword } = req.body;
      if (!teacherId || !newPassword) {
        return res.status(400).json({ error: "teacherId and newPassword are required." });
      }
      await updateDoc(doc(getDb(), "teachers", teacherId), {
        password: newPassword,
        initialPassword: newPassword,
        updatedAt: new Date().toISOString()
      });
      res.json({ success: true, message: "Teacher password reset successfully." });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/v1/auth/forgot-password", async (req, res) => {
    try {
      const { email } = req.body;
      if (!email) {
        return res.status(400).json({ error: "Email address is required." });
      }
      const trimmedEmail = email.trim().toLowerCase();

      // Check if teacher
      const teacherSnap = await getDocs(query(collection(getDb(), "teachers"), where("email", "==", trimmedEmail)));
      if (!teacherSnap.empty) {
        const teacherData = teacherSnap.docs[0].data();
        let schoolName = "your school administration";
        if (teacherData.schoolId) {
          const sDoc = await getDoc(doc(getDb(), "schools", teacherData.schoolId));
          if (sDoc.exists()) schoolName = sDoc.data().name;
        }
        return res.json({
          userType: "Teacher",
          schoolName,
          message: `Password reset request registered for ${teacherData.fullName}. Please contact your School Administrator (${schoolName}) to issue a new generated Password Slip.`
        });
      }

      // Check if school
      const schoolSnap = await getDocs(query(collection(getDb(), "schools"), where("email", "==", trimmedEmail)));
      if (!schoolSnap.empty) {
        const schoolDoc = schoolSnap.docs[0];
        const schoolData = schoolDoc.data();
        return res.json({
          userType: "Admin",
          schoolId: schoolDoc.id,
          schoolName: schoolData.name,
          message: `Official password recovery instructions and a 6-digit reset PIN have been dispatched to ${trimmedEmail}. Contact GEDA Support Line (0244123456) for emergency access verification.`
        });
      }

      return res.status(404).json({ error: "No school or staff account found matching that email address." });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.get("/api/v1/news", async (req, res) => {
    res.json([
      {
        id: '1', title: 'GES Announces New Curriculum Framework',
        content: 'The Ghana Education Service has released a comprehensive update to the basic school curriculum.',
        date: new Date().toISOString(), source: 'GES Official', url: '#'
      }
    ]);
  });
  
  app.get("/api/v1/academic-records", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.studentId) conditions.push(where("studentId", "==", q.studentId as string));
      if (q.academicYear) conditions.push(where("academicYear", "==", q.academicYear as string));
      if (q.academicTerm) conditions.push(where("academicTerm", "==", q.academicTerm as string));
      if (q.classLevel) conditions.push(where("classLevel", "==", q.classLevel as string));
      const snapshot = await getDocs(query(collection(getDb(), "academicRecords"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/v1/academic-records", async (req, res) => {
    try {
      const record = req.body;
      record.createdAt = new Date().toISOString();

      
      let existingId = record.id;
      if (!existingId) {
        // try to find existing
        const snapshot = await getDocs(query(collection(getDb(), "academicRecords"), 
          where("schoolId", "==", record.schoolId),
          where("studentId", "==", record.studentId),
          where("academicYear", "==", record.academicYear),
          where("academicTerm", "==", record.academicTerm)
        ));
        if (!snapshot.empty) {
          existingId = snapshot.docs[0].id;
        }
      }
      
      delete record.id;
      if (existingId) {
        await updateDoc(doc(getDb(), "academicRecords", existingId), record);
        res.status(200).json({ ...record, id: existingId });
      } else {
        const docRef = await addDoc(collection(getDb(), "academicRecords"), record);
        res.status(201).json({ ...record, id: docRef.id });
      }
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  // --- SUPERADMIN ---
  app.get("/api/v1/superadmin/schools", async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "schools"));
      const schools = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));
      
      const studentsSnapshot = await getDocs(collection(getDb(), "students"));
      const students = studentsSnapshot.docs.map(doc => doc.data());
      
      const schoolsWithCounts = schools.map(school => {
        const schoolStudents = students.filter(s => s.schoolId === school.id);
        const calcCount = schoolStudents.length > 0 ? schoolStudents.length : ((school as any).studentCount || 0);
        const paidCount = (school as any).paidStudentCount !== undefined && (school as any).paidStudentCount !== null ? Number((school as any).paidStudentCount) : 0;
        return {
          ...school,
          studentCount: calcCount,
          paidStudentCount: paidCount
        };
      });
      
      res.json(schoolsWithCounts);
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/superadmin/schools/:id/status", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), { status: req.body.status }, { merge: true });
      res.json({ message: "Status updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/superadmin/schools/:id/verify-payment", async (req, res) => {
    try {
      const paidCount = Number(req.body.paidStudentCount !== undefined ? req.body.paidStudentCount : 0);
      await setDoc(doc(getDb(), "schools", req.params.id), { 
        accessLevel: "Full", 
        paidStudentCount: paidCount, 
        billingNotice: "" 
      }, { merge: true });
      res.json({ message: "Payment verified", paidStudentCount: paidCount });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.put("/api/v1/superadmin/schools/:id/billing-notice", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), { billingNotice: req.body.billingNotice }, { merge: true });
      res.json({ message: "Notice sent" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.put("/api/v1/superadmin/schools/:id/access", async (req, res) => {
    try {
      await setDoc(doc(getDb(), "schools", req.params.id), { accessLevel: req.body.accessLevel }, { merge: true });
      res.json({ message: "Access updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
