
import express from "express";
import path from "path";
import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs, doc, setDoc, addDoc, query, where, updateDoc, writeBatch, deleteDoc, getDoc } from "firebase/firestore/lite";
import fs from "fs";

// Safely load local config generated by AI Studio without breaking Vercel builds if the file is ignored
let db: any = null;

function getDb() {
  if (db) return db;

  let firebaseConfig: any = {};
  try {
    firebaseConfig = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'firebase-applet-config.json'), 'utf8'));
  } catch (e: any) {
    console.warn("Could not load local firebase config in api route.");
  }

  const finalConfig = {
    projectId: process.env.VITE_FIREBASE_PROJECT_ID || firebaseConfig.projectId || 'demo-project',
    appId: process.env.VITE_FIREBASE_APP_ID || firebaseConfig.appId || '1:1234567890:web:1234567890',
    apiKey: process.env.VITE_FIREBASE_API_KEY || firebaseConfig.apiKey || 'demo-api-key',
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfig.authDomain || 'demo-project.firebaseapp.com',
    firestoreDatabaseId: process.env.VITE_FIREBASE_DATABASE_ID || firebaseConfig.firestoreDatabaseId || '(default)',
  };

  const appFirebase = initializeApp(finalConfig);
  db = getFirestore(appFirebase, finalConfig.firestoreDatabaseId);
  return db;
}

const app = express();
app.use(express.json());

// Helper for checking dev environment api key
const validateApiKey = (req: any, res: any, next: any) => {
    const authHeader = req.headers.authorization;
    if (authHeader && authHeader.startsWith('Bearer ')) {
      // In a real app we'd query db for the API key to find the schoolId
      // For now, we'll extract it assuming it's passed or default to dev
      req.schoolId = "dev-school";
      next();
    } else {
      res.status(401).json({ error: 'Unauthorized' });
    }
  };

  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // --- SCHOOLS ---
  app.get("/api/v1/schools", async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "schools"));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/schools", async (req, res) => {
    try {
      const { name, region, district, email, password } = req.body;
      const school = {
        name, region, district, email,
        status: "Active", accessLevel: "Trial",
        userId: "admin-id", // mock
        createdAt: new Date().toISOString()
      };
      const docRef = await addDoc(collection(getDb(), "schools"), school);
      res.status(201).json({ ...school, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.get("/api/v1/schools/:id", async (req, res) => {
    try {
      if (req.params.id === "demo-school") {
        return res.json({
          id: 'demo-school',
          name: 'GEDA Demo School Complex',
          slug: 'geda-demo-school',
          region: 'Greater Accra',
          district: 'Accra Metropolitan',
          email: 'admin@gedaschool.edu.gh',
          status: 'Active',
          accessLevel: 'Full',
          createdAt: new Date().toISOString()
        });
      }
      const docRef = doc(getDb(), "schools", req.params.id);
      const snapshot = await getDoc(docRef);
      if (snapshot.exists()) {
        res.json({ ...snapshot.data(), id: snapshot.id });
      } else {
        res.status(404).json({ error: "School not found" });
      }
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/schools/:id", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "schools", req.params.id), req.body);
      res.json({ message: "School updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- AUTH ---
  app.post("/api/v1/auth/login", async (req, res) => {
    try {
      const { email, password, role } = req.body;
      if (email === "admin@gedaschool.edu.gh") {
        return res.json({
          success: true,
          user: { email, fullName: "Admin User", role },
          school: {
            id: 'demo-school',
            name: 'GEDA Demo School Complex',
            slug: 'geda-demo-school',
            region: 'Greater Accra',
            district: 'Accra Metropolitan',
            email: 'admin@gedaschool.edu.gh',
            status: 'Active',
            accessLevel: 'Full',
            createdAt: new Date().toISOString()
          }
        });
      }
      const snapshot = await getDocs(query(collection(getDb(), "schools"), where("email", "==", email)));
      if (snapshot.empty) {
        return res.status(401).json({ error: "Invalid credentials" });
      }
      const schoolDoc = snapshot.docs[0];
      res.json({
        success: true,
        user: { email, fullName: "Admin User", role },
        school: { ...schoolDoc.data(), id: schoolDoc.id }
      });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- STUDENTS ---
  app.get("/api/v1/students", async (req, res) => {
    try {
      const snapshot = await getDocs(query(collection(getDb(), "students"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/students/:id", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "students", req.params.id), req.body);
      res.json({ message: "Student updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.delete("/api/v1/students/:id", async (req, res) => {
    try {
      await deleteDoc(doc(getDb(), "students", req.params.id));
      res.json({ message: "Student deleted" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students", async (req, res) => {
    try {
      const student = req.body;
      student.createdAt = new Date().toISOString();
      if (!student.admissionNo || student.admissionNo === "PENDING-SYNC") {
        student.admissionNo = `ADM-${Math.floor(Math.random() * 1000000).toString().padStart(6, '0')}`;
      }
      delete student.id;
      const docRef = await addDoc(collection(getDb(), "students"), student);
      res.status(201).json({ ...student, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students/bulk", async (req, res) => {
    try {
      const { students } = req.body;
      const batch = writeBatch(getDb());
      const results = [];
      for (const s of students) {
        const docRef = doc(collection(getDb(), "students"));
        s.createdAt = new Date().toISOString();
        delete s.id;
        batch.set(docRef, s);
        results.push({ ...s, id: docRef.id });
      }
      await batch.commit();
      res.status(201).json(results);
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/students/promote", async (req, res) => {
    try {
      const { studentIds, targetClass } = req.body;
      const batch = writeBatch(getDb());
      for (const id of studentIds) {
        batch.update(doc(getDb(), "students", id), { classLevel: targetClass });
      }
      await batch.commit();
      res.json({ message: "Promoted successfully" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.get("/api/v1/sis/students", validateApiKey, async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "students"));
      res.json({ data: snapshot.docs.map(d => ({ ...d.data(), id: d.id })) });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- PAYMENTS ---
  app.get("/api/v1/payments", async (req, res) => {
    try {
      if (req.query.schoolId === "demo-school") return res.json([]);
      const snapshot = await getDocs(query(collection(getDb(), "payments"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/payments", async (req, res) => {
    try {
      const payment = req.body;
      payment.timestamp = new Date().toISOString();
      if (payment.schoolId === "demo-school") {
        payment.id = "demo-pay-" + Date.now();
        return res.status(201).json(payment);
      }
      const docRef = await addDoc(collection(getDb(), "payments"), payment);
      res.status(201).json({ ...payment, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- BACKUPS ---
  app.get("/api/v1/backups", async (req, res) => {
    try {
      if (req.query.schoolId === "demo-school") return res.json([]);
      const snapshot = await getDocs(query(collection(getDb(), "backupLogs"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/backups", async (req, res) => {
    try {
      const { schoolId, type } = req.body;
      const log = {
        schoolId, type: type || "Manual", timestamp: new Date().toISOString(),
        recordsCount: 0, fileName: `backup_${schoolId}_${Date.now()}.json`, status: "Completed"
      };
      if (schoolId === "demo-school") {
        return res.status(201).json({ log: { ...log, id: "demo-backup-" + Date.now() } });
      }
      const docRef = await addDoc(collection(getDb(), "backupLogs"), log);
      res.status(201).json({ log: { ...log, id: docRef.id } });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- API KEYS ---
  app.get("/api/v1/api-keys", async (req, res) => {
    try {
      if (req.query.schoolId === "demo-school") return res.json([]);
      const snapshot = await getDocs(query(collection(getDb(), "apiKeys"), where("schoolId", "==", req.query.schoolId || "")));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/api-keys", async (req, res) => {
    try {
      const { schoolId, name } = req.body;
      const key = {
        schoolId, name, status: "Active",
        token: `geda_tok_${Math.random().toString(36).substr(2, 9)}`,
        createdAt: new Date().toISOString()
      };
      if (schoolId === "demo-school") {
        return res.status(201).json({ ...key, id: "demo-key-" + Date.now() });
      }
      const docRef = await addDoc(collection(getDb(), "apiKeys"), key);
      res.status(201).json({ ...key, id: docRef.id });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.post("/api/v1/api-keys/revoke", async (req, res) => {
    try {
      const { keyId } = req.body;
      if (keyId.startsWith("demo-key-")) return res.json({ message: "Revoked" });
      await updateDoc(doc(getDb(), "apiKeys", keyId), { status: "Revoked" });
      res.json({ message: "Revoked" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  // --- OTHERS ---
  app.get("/api/v1/attendance", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.academicYear) conditions.push(where("academicYear", "==", q.academicYear));
      if (q.academicTerm) conditions.push(where("academicTerm", "==", q.academicTerm));
      const snapshot = await getDocs(query(collection(getDb(), "attendance"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/attendance/batch", async (req, res) => {
    try {
      const { schoolId, records } = req.body;
      if (schoolId === "demo-school") {
        return res.json({ message: "Attendance marked" });
      }
      const batch = writeBatch(getDb());
      for (const r of records) {
        if (r.id) {
          batch.update(doc(getDb(), "attendance", r.id), r);
        } else {
          const docRef = doc(collection(getDb(), "attendance"));
          batch.set(docRef, r);
        }
      }
      await batch.commit();
      res.json({ message: "Attendance marked" });
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  app.post("/api/v1/sync", async (req, res) => {
    try {
      const { schoolId, students } = req.body;
      const batch = writeBatch(getDb());
      let syncedCount = 0;
      
      for (const s of students) {
        const docRef = doc(collection(getDb(), "students"));
        s.createdAt = s.createdAt || new Date().toISOString();
        s.syncStatus = "synced";
        delete s.id; // Remove offline ID
        batch.set(docRef, s);
        syncedCount++;
      }
      if (syncedCount > 0) {
        await batch.commit();
      }
      
      const snapshot = await getDocs(query(collection(getDb(), "students"), where("schoolId", "==", schoolId || "")));
      const allStudents = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));
      
      res.json({ message: "Sync complete", syncedCount, students: allStudents });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });
  
  app.get("/api/v1/teachers", async (req, res) => {
    res.json([]);
  });

  app.get("/api/v1/news", async (req, res) => {
    res.json([
      {
        id: '1', title: 'GES Announces New Curriculum Framework',
        content: 'The Ghana Education Service has released a comprehensive update to the basic school curriculum.',
        date: new Date().toISOString(), source: 'GES Official', url: '#'
      }
    ]);
  });
  
  app.get("/api/v1/academic-records", async (req, res) => {
    try {
      const q = req.query;
      let conditions = [where("schoolId", "==", q.schoolId || "")];
      if (q.academicYear) conditions.push(where("academicYear", "==", q.academicYear));
      if (q.academicTerm) conditions.push(where("academicTerm", "==", q.academicTerm));
      const snapshot = await getDocs(query(collection(getDb(), "academicRecords"), ...conditions));
      res.json(snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id })));
    } catch (e) {
      res.status(500).json({ error: e.message });
    }
  });

  app.post("/api/v1/academic-records", async (req, res) => {
    try {
      const record = req.body;
      record.createdAt = new Date().toISOString();
      if (record.schoolId === "demo-school") {
        record.id = "demo-rec-" + Date.now();
        return res.status(201).json(record);
      }
      
      let existingId = record.id;
      if (!existingId) {
        // try to find existing
        const snapshot = await getDocs(query(collection(getDb(), "academicRecords"), 
          where("schoolId", "==", record.schoolId),
          where("studentId", "==", record.studentId),
          where("academicYear", "==", record.academicYear),
          where("academicTerm", "==", record.academicTerm)
        ));
        if (!snapshot.empty) {
          existingId = snapshot.docs[0].id;
        }
      }
      
      delete record.id;
      if (existingId) {
        await updateDoc(doc(getDb(), "academicRecords", existingId), record);
        res.status(200).json({ ...record, id: existingId });
      } else {
        const docRef = await addDoc(collection(getDb(), "academicRecords"), record);
        res.status(201).json({ ...record, id: docRef.id });
      }
    } catch (e) { res.status(500).json({ error: e.message }); }
  });

  // --- SUPERADMIN ---
  app.get("/api/v1/superadmin/schools", async (req, res) => {
    try {
      const snapshot = await getDocs(collection(getDb(), "schools"));
      const schools = snapshot.docs.map(doc => ({ ...doc.data(), id: doc.id }));
      
      const studentsSnapshot = await getDocs(collection(getDb(), "students"));
      const students = studentsSnapshot.docs.map(doc => doc.data());
      
      const schoolsWithCounts = schools.map(school => {
        const schoolStudents = students.filter(s => s.schoolId === school.id);
        const paidCount = schoolStudents.filter(s => s.paymentStatus === 'Paid' || (s.feeTotal > 0 && s.feePaid >= s.feeTotal)).length;
        return {
          ...school,
          studentCount: schoolStudents.length,
          paidStudentCount: paidCount
        };
      });
      
      res.json(schoolsWithCounts);
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/superadmin/schools/:id/status", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "schools", req.params.id), { status: req.body.status });
      res.json({ message: "Status updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

  app.put("/api/v1/superadmin/schools/:id/verify-payment", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "schools", req.params.id), { accessLevel: "Full", paidStudentCount: req.body.paidStudentCount, billingNotice: "" });
      res.json({ message: "Payment verified" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.put("/api/v1/superadmin/schools/:id/billing-notice", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "schools", req.params.id), { billingNotice: req.body.billingNotice });
      res.json({ message: "Notice sent" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });
  
  app.put("/api/v1/superadmin/schools/:id/access", async (req, res) => {
    try {
      await updateDoc(doc(getDb(), "schools", req.params.id), { accessLevel: req.body.accessLevel });
      res.json({ message: "Access updated" });
    } catch (e: any) { res.status(500).json({ error: e.message }); }
  });

export default app;
